apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: infographic-pipeline
spec:
  resources:
    - name: APPLICATION_SOURCE_REPO_URL
      type: git
    - name: APPLICATION_SOURCE_REPO_REF
      type: git

  params:
    - name: APP_NAME
      description: The name of the application
      default: 'infographic'
    - name: NAMESPACE_BUILD
      description: The namespace of infographic build
      default: 'infographic-pipeline'
    - name: NAMESPACE_DEV
      description: The namespace of infographic dev
      default: 'infographic-dev'
    - name: NAMESPACE_TEST
      description: The namespace of infographic test
      default: 'infographic-test'
    - name: NAMESPACE_UAT
      description: The namespace of infographic uat
      default: 'infographic-uat'

  tasks:
  - name: scm-checkout
    taskRef:
      name: scm-checkout
    resources:
      inputs:
        - name: source-url
          resource: APPLICATION_SOURCE_REPO_URL
        - name: source-ref
          resource: APPLICATION_SOURCE_REPO_REF
  - name: build-image
    taskRef:
      name:
    runAfter:
      - scm-checkout
  - name: security-scanning
    taskRef:
      name: 
    runAfter:
      - build-image
  - name: deploy-to-dev
    taskRef:
      name:
    runAfter:
      - security-scanning
  - name: deploy-to-test
    taskRef:
      name:
    runAfter:
      - deploy-to-dev
  - name: deploy-to-uat
    taskRef:
      name:
    runAfter:
      - deploy-to-test
