apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: infographic-pipeline
spec:
  resources:
    - name: APPLICATION_SOURCE_REPO_URL
      type: git
    - name: APPLICATION_SOURCE_REPO_REF
      type: git

  params:
    - name: submodules
      description: some text
      default: 'true'
    - name: depth
      description: some text
      default: '1'
    - name: sslVerify
      description: some text
      default: 'false'
    - name: deleteExisting
      description: some text
      default: 'false'
    - name: APP_NAME
      description: The name of the application
      default: 'infographic'
    - name: NAMESPACE_BUILD
      description: The namespace of infographic build
      default: 'infographic-pipeline'
    - name: NAMESPACE_DEV
      description: The namespace of infographic dev
      default: 'infographic-dev'
    - name: NAMESPACE_TEST
      description: The namespace of infographic test
      default: 'infographic-test'
    - name: NAMESPACE_UAT
      description: The namespace of infographic uat
      default: 'infographic-uat'

  tasks:
  - name: scm-checkout
    taskRef:
      name: scm-checkout
    resources:
      inputs:
        - name: APPLICATION_SOURCE_REPO_URL
          resource: infographic-repo
        - name: APPLICATION_SOURCE_REPO_REF
          resource: infographic-repo
        - name: submodules
          resource: submodules
  - name: build-image
    taskRef:
      name: build-image
    runAfter:
      - scm-checkout
  - name: security-scanning
    taskRef:
      name: security-scanning
    runAfter:
      - build-image
  - name: deploy-to-dev
    taskRef:
      name: deploy-to-dev
    runAfter:
      - security-scanning
  - name: deploy-to-test
    taskRef:
      name: deploy-to-test
    runAfter:
      - deploy-to-dev
  - name: deploy-to-uat
    taskRef:
      name: deploy-to-uat
    runAfter:
      - deploy-to-test
