apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: scm-checkout
spec:
  workspaces:
  - name: infographic-workspace
  params:
    - name: application_source_repo_url
      description: Repository source URL
    - name: application_source_repo_ref
      description: Repository source branch/reference
  steps:
    - name: scm-checkout
      params:
        - name: url
          value: application_source_repo_url
        - name: revision
          value: application_source_repo_ref
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'false'
        - name: deleteExisting
          value: 'false'
      taskRef:
        kind: ClusterTask
        name: git-clone
