apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-image
spec:
  resources:
    inputs:
      - name: source
        type: git
  params:
    - name: APP_NAME
      description: The name of the application
      default: 'infographic'
    - name: SCRIPT 
      type: string
      default: 'oc $@'
  steps:
    - name: build-image
      image: quay.io/openshift/origin-cli:latest
      script: "$(params.SCRIPT)"
      args:
        - "start-build $(params.APP_NAME) --from-dir=. --follow"
